fn main() {
	panic!("Failure! Failure!");
}